
// This file has been generated by the GUI designer. Do not modify.
namespace Viewers
{
	public partial class BaseViewer
	{
		private global::Gtk.Image image1;
		
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Viewers.BaseViewer
			this.Name = "Viewers.BaseViewer";
			this.Title = global::Mono.Unix.Catalog.GetString ("Viewer");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Viewers.BaseViewer.Gtk.Container+ContainerChild
			this.image1 = new global::Gtk.Image ();
			this.image1.Name = "image1";
			this.Add (this.image1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
